import axios from 'axios';

// const API_KEY = process.env.API_KEY;
const API_KEY = '123';

const DATA = {
  status: 'OK',
  request_id: '26552703-bd7b-4944-aa24-6bffcf3d259a',
  data: {
    trends: [
      {
        symbol: 'KIRLPNU:NSE',
        type: 'stock',
        name: 'Kirloskar Pneumatic Company Ltd',
        price: 1090.3,
        change: 181.7001,
        change_percent: 19.9978,
        previous_close: 908.6,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:43',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/1dv7cbdk',
      },
      {
        symbol: 'ROSSELLIND:NSE',
        type: 'stock',
        name: 'Rossell India Ltd',
        price: 468.35,
        change: 78.05,
        change_percent: 19.9974,
        previous_close: 390.3,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 11:43:48',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/11r_9sx9h',
      },
      {
        symbol: 'MGEL:NSE',
        type: 'stock',
        name: 'Mangalam Global Enterprise Ltd',
        price: 23.25,
        change: 3.85,
        change_percent: 19.8454,
        previous_close: 19.4,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:40',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/11fq3481_t',
      },
      {
        symbol: 'MEDICAMEQ:NSE',
        type: 'stock',
        name: 'Medicamen Biotech Ltd',
        price: 494.9,
        change: 72.8,
        change_percent: 17.2471,
        previous_close: 422.1,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:41',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/11dx9htwbj',
      },
      {
        symbol: 'SANWARIA:NSE',
        type: 'stock',
        name: 'Sanwaria Consumer Ltd',
        price: 0.4,
        change: 0.05,
        change_percent: 14.2857,
        previous_close: 0.35,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-22 13:48:38',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-22 09:15:00',
        exchange_close: '2024-04-22 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/1dtsbwm7',
      },
      {
        symbol: 'HUDCO:NSE',
        type: 'stock',
        name: 'Housing And Urban Development Corp Ltd',
        price: 227.35,
        change: 24.3,
        change_percent: 11.9675,
        previous_close: 203.05,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:39',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/11d_w699bj',
      },
      {
        symbol: 'KIRLOSIND:NSE',
        type: 'stock',
        name: 'Kirloskar Industries Ltd',
        price: 5151,
        change: 513.8501,
        change_percent: 11.0812,
        previous_close: 4637.15,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:39',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/1dtw9kml',
      },
      {
        symbol: 'DPABHUSHAN:NSE',
        type: 'stock',
        name: 'D P Abhushan Ltd',
        price: 1130.95,
        change: 104.45,
        change_percent: 10.1753,
        previous_close: 1026.5,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:29:56',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/11f1ddr5bl',
      },
      {
        symbol: 'DOLATALGO:NSE',
        type: 'stock',
        name: 'Dolat Algotech Ltd',
        price: 112.2,
        change: 10.35,
        change_percent: 10.162,
        previous_close: 101.85,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:40',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/11c6r3s5j4',
      },
      {
        symbol: 'ACL:NSE',
        type: 'stock',
        name: 'Andhra Cements Ltd',
        price: 98.3,
        change: 8.9,
        change_percent: 9.9553,
        previous_close: 89.4,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:42',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/11dx9gdxsh',
      },
      {
        symbol: 'TCLCONS:NSE',
        type: 'stock',
        name: 'Tantia Constructions Ltd',
        price: 33.75,
        change: 3.05,
        change_percent: 9.9349,
        previous_close: 30.7,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 11:43:49',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/11c6qsm3bl',
      },
      {
        symbol: 'KECL:NSE',
        type: 'stock',
        name: 'Kirloskar Electric Company Ltd',
        price: 130.05,
        change: 11.65,
        change_percent: 9.8395,
        previous_close: 118.4,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:43',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/1hbvlvxdt',
      },
      {
        symbol: 'NIACL:NSE',
        type: 'stock',
        name: 'New India Assurance Company Ltd',
        price: 249.05,
        change: 22.15,
        change_percent: 9.762,
        previous_close: 226.9,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:39',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/11f2b6b9d3',
      },
      {
        symbol: 'EMKAY:NSE',
        type: 'stock',
        name: 'Emkay Global Financial Services Ltd',
        price: 164.15,
        change: 14.15,
        change_percent: 9.4333,
        previous_close: 150,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:24:41',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/1hbvn54mq',
      },
      {
        symbol: 'ASAHISONG:NSE',
        type: 'stock',
        name: 'Asahi Songwon Colors Ltd',
        price: 386.5,
        change: 32.85,
        change_percent: 9.2888,
        previous_close: 353.65,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 11:43:46',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/1dtzg07v',
      },
      {
        symbol: 'AHLADA:NSE',
        type: 'stock',
        name: 'Ahlada Engineers Ltd',
        price: 121.35,
        change: 9.8,
        change_percent: 8.7853,
        previous_close: 111.55,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:40',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/11gn1vd90k',
      },
      {
        symbol: 'GLS:NSE',
        type: 'stock',
        name: 'Glenmark Life Sciences Ltd',
        price: 814,
        change: 63.5,
        change_percent: 8.461,
        previous_close: 750.5,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:43',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/11ny348dd2',
      },
      {
        symbol: 'RISHABH:NSE',
        type: 'stock',
        name: 'Rishabh Instruments Ltd',
        price: 467.6,
        change: 34.45,
        change_percent: 7.9534,
        previous_close: 433.15,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:43',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/11vd767hh7',
      },
      {
        symbol: 'BPL:NSE',
        type: 'stock',
        name: 'BPL Ltd',
        price: 112,
        change: 8.25,
        change_percent: 7.9518,
        previous_close: 103.75,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:40',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/1hbvrpc7l',
      },
      {
        symbol: 'MMFL:NSE',
        type: 'stock',
        name: 'MM Forgings Ltd',
        price: 1152,
        change: 84.25,
        change_percent: 7.8904,
        previous_close: 1067.75,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:42',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/1dvbplm3',
      },
      {
        symbol: 'HARSHA:NSE',
        type: 'stock',
        name: 'Harsha Engineers International Ltd',
        price: 443.35,
        change: 32.3,
        change_percent: 7.8579,
        previous_close: 411.05,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:39',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/11tdnw4p8s',
      },
      {
        symbol: 'ZENSARTECH:NSE',
        type: 'stock',
        name: 'Zensar Technologies Ltd',
        price: 619.5,
        change: 44.8,
        change_percent: 7.7954,
        previous_close: 574.7,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:44',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/1dtytppr',
      },
      {
        symbol: 'TECHM:NSE',
        type: 'stock',
        name: 'Tech Mahindra Ltd',
        price: 1280.15,
        change: 89.85,
        change_percent: 7.5485,
        previous_close: 1190.3,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:39',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/1hbvv7129',
      },
      {
        symbol: 'BASML:NSE',
        type: 'stock',
        name: 'Bannari Amman Spinning Mills Ltd',
        price: 49.45,
        change: 3.45,
        change_percent: 7.5,
        previous_close: 46,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:41',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/1dv9l6kh',
      },
      {
        symbol: 'BECTORFOOD:NSE',
        type: 'stock',
        name: 'Mrs. Bectors Food Specialities Ltd',
        price: 1237,
        change: 85.85,
        change_percent: 7.4578,
        previous_close: 1151.15,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:40',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/11llbs4__b',
      },
      {
        symbol: 'EROSMEDIA:NSE',
        type: 'stock',
        name: 'Eros International Media Ltd',
        price: 22.95,
        change: 1.55,
        change_percent: 7.243,
        previous_close: 21.4,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:41',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/1dtvqt24',
      },
      {
        symbol: 'KIRLOSENG:NSE',
        type: 'stock',
        name: 'Kirloskar Oil Engines Ltd',
        price: 1023,
        change: 68.95,
        change_percent: 7.2271,
        previous_close: 954.05,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:39',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/1dv7s6hx',
      },
      {
        symbol: 'GMRINFRA:NSE',
        type: 'stock',
        name: 'GMR Airports Infrastructure Ltd',
        price: 91.3,
        change: 6.15,
        change_percent: 7.2226,
        previous_close: 85.15,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:39',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/1dv9bs1x',
      },
      {
        symbol: 'VSTTILLERS:NSE',
        type: 'stock',
        name: 'VST Tillers Tractors Limited',
        price: 3547.4,
        change: 238.7998,
        change_percent: 7.2175,
        previous_close: 3308.6,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:44',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/1dv1kpcq',
      },
      {
        symbol: 'FEL:NSE',
        type: 'stock',
        name: 'Future Enterprises Ltd',
        price: 0.75,
        change: 0.05,
        change_percent: 7.1429,
        previous_close: 0.7,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 11:43:47',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/1dt_k538',
      },
      {
        symbol: 'DCMSHRIRAM:NSE',
        type: 'stock',
        name: 'DCM Shriram Ltd',
        price: 965,
        change: 61.1,
        change_percent: 6.7596,
        previous_close: 903.9,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:42',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/1dv03ryr',
      },
      {
        symbol: 'AARTISURF:NSE',
        type: 'stock',
        name: 'Aarti Surfactants Ltd',
        price: 680,
        change: 42.9,
        change_percent: 6.7336,
        previous_close: 637.1,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:39',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/11jj0hkymj',
      },
      {
        symbol: 'WESTLIFE:NSE',
        type: 'stock',
        name: 'Westlife Foodworld Ltd',
        price: 878,
        change: 55.2,
        change_percent: 6.7088,
        previous_close: 822.8,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:41',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/11c6qtpb_b',
      },
      {
        symbol: 'SESHAPAPER:NSE',
        type: 'stock',
        name: 'Seshasayee Paper and Boards Ltd',
        price: 350.5,
        change: 22,
        change_percent: 6.6971,
        previous_close: 328.5,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:39',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/1dv41y3s',
      },
      {
        symbol: 'NLCINDIA:NSE',
        type: 'stock',
        name: 'NLC India Ltd',
        price: 249.2,
        change: 15.45,
        change_percent: 6.6096,
        previous_close: 233.75,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:39',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/1dtt8gy0',
      },
      {
        symbol: 'COROMANDEL:NSE',
        type: 'stock',
        name: 'Coromandel International Ltd',
        price: 1183.05,
        change: 71.1001,
        change_percent: 6.3942,
        previous_close: 1111.95,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:40',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/1dttk_dw',
      },
      {
        symbol: 'JTLIND:NSE',
        type: 'stock',
        name: 'JTL Industries Ltd',
        price: 222.2,
        change: 13.2,
        change_percent: 6.3158,
        previous_close: 209,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:41',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/11g6mx_dkh',
      },
      {
        symbol: 'ENGINERSIN:NSE',
        type: 'stock',
        name: 'Engineers India Ltd',
        price: 236.05,
        change: 14,
        change_percent: 6.3049,
        previous_close: 222.05,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:39',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/1dv3cr30',
      },
      {
        symbol: 'ANDHRAPAP:NSE',
        type: 'stock',
        name: 'Andhra Paper Ltd',
        price: 529.5,
        change: 31.15,
        change_percent: 6.2506,
        previous_close: 498.35,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:40',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/11dylwcqbf',
      },
      {
        symbol: 'CONCOR:NSE',
        type: 'stock',
        name: 'Container Corporation of India Ltd',
        price: 1067,
        change: 62.2,
        change_percent: 6.1903,
        previous_close: 1004.8,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:39',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/1dv8ql3h',
      },
      {
        symbol: 'GANDHITUBE:NSE',
        type: 'stock',
        name: 'Gandhi Special Tubes Ltd',
        price: 856.5,
        change: 49.8,
        change_percent: 6.1733,
        previous_close: 806.7,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:40',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/1dttdf2c',
      },
      {
        symbol: 'SUPREMEENG:NSE',
        type: 'stock',
        name: 'Supreme Engineering Ltd',
        price: 0.9,
        change: 0.05,
        change_percent: 5.8823,
        previous_close: 0.85,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 11:43:49',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/11f9ynff6g',
      },
      {
        symbol: 'DIXON:NSE',
        type: 'stock',
        name: 'Dixon Technologies (India) Ltd',
        price: 8568.05,
        change: 474.6499,
        change_percent: 5.8647,
        previous_close: 8093.4,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:39',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/11f0_cszmx',
      },
      {
        symbol: 'AEGISCHEM:NSE',
        type: 'stock',
        name: 'Aegis Logistics Ltd',
        price: 635,
        change: 34.85,
        change_percent: 5.8069,
        previous_close: 600.15,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:39',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/1dv5hzq3',
      },
      {
        symbol: 'SPCENET:NSE',
        type: 'stock',
        name: 'Spacenet Enterprises India Ltd',
        price: 29.5,
        change: 1.6,
        change_percent: 5.7348,
        previous_close: 27.9,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:43',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/1yhbjtbv3',
      },
      {
        symbol: 'BIOCON:NSE',
        type: 'stock',
        name: 'Biocon Ltd',
        price: 308.25,
        change: 16.6,
        change_percent: 5.6918,
        previous_close: 291.65,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:39',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/1dv45xdt',
      },
      {
        symbol: 'SIGNPOST:NSE',
        type: 'stock',
        name: 'Signpost India Ltd',
        price: 337,
        change: 18.1,
        change_percent: 5.6758,
        previous_close: 318.9,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:43',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/11y32bn2fg',
      },
      {
        symbol: 'DREAMFOLKS:NSE',
        type: 'stock',
        name: 'Dreamfolks Services Ltd',
        price: 553.5,
        change: 29.6,
        change_percent: 5.6499,
        previous_close: 523.9,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:39',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/11tct0d7_5',
      },
      {
        symbol: 'SHAH:NSE',
        type: 'stock',
        name: 'Shah Metacorp Ltd',
        price: 3.75,
        change: 0.2,
        change_percent: 5.6338,
        previous_close: 3.55,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:29:59',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/11c6qvh3lk',
      },
      {
        symbol: 'BIGBLOC:NSE',
        type: 'stock',
        name: 'Bigbloc Construction Ltd',
        price: 249.5,
        change: 13.3,
        change_percent: 5.6308,
        previous_close: 236.2,
        pre_or_post_market: null,
        pre_or_post_market_change: null,
        pre_or_post_market_change_percent: null,
        last_update_utc: '2024-04-26 10:32:39',
        currency: 'INR',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        country_code: 'IN',
        google_mid: '/g/11cr_s5yv_',
      },
    ],
    news: [
      {
        article_title:
          'VST Tillers shares jump 6% on incorporation of US subsidiary',
        article_url:
          'https://www.business-standard.com/markets/news/vst-tillers-shares-jump-6-on-incorporation-of-us-subsidiary-124042600481_1.html',
        article_photo_url:
          'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSMrkyrodpFkfVqRPqM-AX1oeMG4ygFXnMovi-3SN3qwf9J1prgjxJzmnikM1Y',
        source: 'Business Standard',
        post_time_utc: '2024-04-26 07:06:11',
        stocks_in_news: [
          {
            symbol: 'VSTTILLERS:NSE',
            type: 'stock',
            name: 'VST Tillers Tractors Limited',
            price: 3547.4,
            change: 238.7998,
            change_percent: 7.2175,
            previous_close: 3308.6,
            pre_or_post_market: null,
            pre_or_post_market_change: null,
            pre_or_post_market_change_percent: null,
            last_update_utc: '2024-04-26 10:32:44',
            currency: 'INR',
            exchange: 'NSE',
            exchange_open: '2024-04-26 09:15:00',
            exchange_close: '2024-04-26 15:30:00',
            timezone: 'Asia/Calcutta',
            utc_offset_sec: 19800,
            country_code: 'IN',
            google_mid: '/g/1dv1kpcq',
          },
        ],
      },
      {
        article_title:
          'HUDCO shares surge 14% to a record high; Stock set for best week in three \nmonths',
        article_url:
          'https://www.cnbctv18.com/market/hudco-share-price-surge-record-high-best-week-in-three-months-2024-returns-gross-npa-q3-result-19402770.htm',
        article_photo_url:
          'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSstEUN25MbYbBd5oXMcH9ehj52gekwPzu2kohVeVErDn2uC7tlrUye4M715o4',
        source: 'cnbctv18',
        post_time_utc: '2024-04-26 07:07:27',
        stocks_in_news: [
          {
            symbol: 'HUDCO:NSE',
            type: 'stock',
            name: 'Housing And Urban Development Corp Ltd',
            price: 227.35,
            change: 24.3,
            change_percent: 11.9675,
            previous_close: 203.05,
            pre_or_post_market: null,
            pre_or_post_market_change: null,
            pre_or_post_market_change_percent: null,
            last_update_utc: '2024-04-26 10:32:39',
            currency: 'INR',
            exchange: 'NSE',
            exchange_open: '2024-04-26 09:15:00',
            exchange_close: '2024-04-26 15:30:00',
            timezone: 'Asia/Calcutta',
            utc_offset_sec: 19800,
            country_code: 'IN',
            google_mid: '/g/11d_w699bj',
          },
        ],
      },
      {
        article_title:
          'Zensar Tech share price surges 12% after healthy Q4 result, upbeat \nmanagement commentary | Mint',
        article_url:
          'https://www.livemint.com/market/stock-market-news/zensar-tech-share-price-surges-12-after-healthy-q4-result-upbeat-management-commentary-11714110473587.html',
        article_photo_url:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVedtimITu70tzgpb9ZH3adxLIqucpCK045xlgWMK1UN77vPEMWiXndvjw93E',
        source: 'mint',
        post_time_utc: '2024-04-26 05:55:18',
        stocks_in_news: [
          {
            symbol: 'ZENSARTECH:NSE',
            type: 'stock',
            name: 'Zensar Technologies Ltd',
            price: 619.5,
            change: 44.8,
            change_percent: 7.7954,
            previous_close: 574.7,
            pre_or_post_market: null,
            pre_or_post_market_change: null,
            pre_or_post_market_change_percent: null,
            last_update_utc: '2024-04-26 10:32:44',
            currency: 'INR',
            exchange: 'NSE',
            exchange_open: '2024-04-26 09:15:00',
            exchange_close: '2024-04-26 15:30:00',
            timezone: 'Asia/Calcutta',
            utc_offset_sec: 19800,
            country_code: 'IN',
            google_mid: '/g/1dtytppr',
          },
        ],
      },
      {
        article_title:
          'Hero MotoCorp share price attractively valued, says Emkay Global; upgrades \nrating, raises target price | Mint',
        article_url:
          'https://www.livemint.com/market/stock-market-news/hero-motocorp-share-price-attractively-valued-says-emkay-global-upgrades-rating-raises-target-price-11714028189248.html',
        article_photo_url:
          'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcR-WdiC3TuBZ_UkuZQX4_LaUFI-xqakT8vfnlyCmDoCGi0oq4v9-31coGnx_mk',
        source: 'mint',
        post_time_utc: '2024-04-25 07:05:24',
        stocks_in_news: [
          {
            symbol: 'HEROMOTOCO:NSE',
            type: 'stock',
            name: 'Hero Motocorp Ltd',
            price: 4493,
            change: -5.2998,
            change_percent: -0.1178,
            previous_close: 4498.3,
            pre_or_post_market: null,
            pre_or_post_market_change: null,
            pre_or_post_market_change_percent: null,
            last_update_utc: '2024-04-26 10:32:42',
            currency: 'INR',
            exchange: 'NSE',
            exchange_open: '2024-04-26 09:15:00',
            exchange_close: '2024-04-26 15:30:00',
            timezone: 'Asia/Calcutta',
            utc_offset_sec: 19800,
            country_code: 'IN',
            google_mid: '/g/1dv488k0',
          },
          {
            symbol: 'EMKAY:NSE',
            type: 'stock',
            name: 'Emkay Global Financial Services Ltd',
            price: 164.15,
            change: 14.15,
            change_percent: 9.4333,
            previous_close: 150,
            pre_or_post_market: null,
            pre_or_post_market_change: null,
            pre_or_post_market_change_percent: null,
            last_update_utc: '2024-04-26 10:24:41',
            currency: 'INR',
            exchange: 'NSE',
            exchange_open: '2024-04-26 09:15:00',
            exchange_close: '2024-04-26 15:30:00',
            timezone: 'Asia/Calcutta',
            utc_offset_sec: 19800,
            country_code: 'IN',
            google_mid: '/g/1hbvn54mq',
          },
        ],
      },
      {
        article_title:
          'Kirloskar Pneumatic Company Q4 Results Live : profit rise by 86.75% YOY | \nMint',
        article_url:
          'https://www.livemint.com/companies/company-results/kirloskar-pneumatic-company-q4-results-live-profit-rise-by-86-75-yoy-11714252783730.html',
        article_photo_url:
          'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTxoqVgqjjZtJwZxrFOlqiievCrCi4mcSKCm7ovks3sc2XfhO1rU_NL27SHOgw',
        source: 'mint',
        post_time_utc: '2024-04-27 21:19:43',
        stocks_in_news: [
          {
            symbol: 'KIRLPNU:NSE',
            type: 'stock',
            name: 'Kirloskar Pneumatic Company Ltd',
            price: 1090.3,
            change: 181.7001,
            change_percent: 19.9978,
            previous_close: 908.6,
            pre_or_post_market: null,
            pre_or_post_market_change: null,
            pre_or_post_market_change_percent: null,
            last_update_utc: '2024-04-26 10:32:43',
            currency: 'INR',
            exchange: 'NSE',
            exchange_open: '2024-04-26 09:15:00',
            exchange_close: '2024-04-26 15:30:00',
            timezone: 'Asia/Calcutta',
            utc_offset_sec: 19800,
            country_code: 'IN',
            google_mid: '/g/1dv7cbdk',
          },
        ],
      },
      {
        article_title:
          'GMR Airports Infrastructure shoots up by 8% on healthy business outlook',
        article_url:
          'https://www.business-standard.com/markets/news/gmr-airports-infrastructure-shoots-up-by-8-on-healthy-business-outlook-124042600505_1.html',
        article_photo_url:
          'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQzmJTptxuI6oDFeRmBp6oIAA1E789yzz1ygAxuGR5z8sS4TSZq-iJpuS4h7L8',
        source: 'Business Standard',
        post_time_utc: '2024-04-26 07:33:18',
        stocks_in_news: [],
      },
    ],
  },
};

const DATA_SEARCH = {
  status: 'OK',
  request_id: '4e6c373b-76f2-4680-8e06-14dc33e6e01c',
  data: {
    stock: [
      {
        symbol: 'IDEA:NSE',
        name: 'Vodafone Idea Ltd',
        type: 'stock',
        price: 13.45,
        change: -0.45,
        change_percent: -3.2374,
        previous_close: 13.9,
        last_update_utc: '2024-04-26 11:43:47',
        country_code: 'IN',
        exchange: 'NSE',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        currency: 'INR',
        google_mid: '/g/1hbvjbvf9',
      },
      {
        symbol: 'VOD:LON',
        name: 'Vodafone Group plc',
        type: 'stock',
        price: 69.08,
        change: 0.08,
        change_percent: 0.1159,
        previous_close: 69,
        last_update_utc: '2024-04-26 18:12:09',
        country_code: 'GB',
        exchange: 'LON',
        exchange_open: '2024-04-26 08:00:00',
        exchange_close: '2024-04-26 16:30:00',
        timezone: 'Europe/London',
        utc_offset_sec: 3600,
        currency: 'GBX',
        google_mid: '/m/0ckgbvh',
      },
      {
        symbol: 'VOD:NASDAQ',
        name: 'Vodafone Group Plc',
        type: 'stock',
        price: 8.62,
        change: 0.01,
        change_percent: 0.1161,
        previous_close: 8.61,
        last_update_utc: '2024-04-27 00:30:00',
        country_code: 'US',
        exchange: 'NASDAQ',
        exchange_open: '2024-04-26 09:30:00',
        exchange_close: '2024-04-26 16:00:00',
        timezone: 'America/New_York',
        utc_offset_sec: -14400,
        currency: 'USD',
        google_mid: '/g/1hbvp9hzg',
      },
      {
        symbol: '532822:BOM',
        name: 'Vodafone Idea Ltd',
        type: 'stock',
        price: 14.01,
        change: 0.12,
        change_percent: 0.8639,
        previous_close: 13.89,
        last_update_utc: '2024-04-26 10:31:35',
        country_code: 'IN',
        exchange: 'BOM',
        exchange_open: '2024-04-26 09:15:00',
        exchange_close: '2024-04-26 15:30:00',
        timezone: 'Asia/Calcutta',
        utc_offset_sec: 19800,
        currency: 'INR',
        google_mid: '/g/12hk0snbp',
      },
      {
        symbol: 'VZ:NYSE',
        name: 'Verizon Communications Inc.',
        type: 'stock',
        price: 39.68,
        change: 0.46,
        change_percent: 1.1729,
        previous_close: 39.22,
        last_update_utc: '2024-04-27 00:04:00',
        country_code: 'US',
        exchange: 'NYSE',
        exchange_open: '2024-04-26 09:30:00',
        exchange_close: '2024-04-26 16:00:00',
        timezone: 'America/New_York',
        utc_offset_sec: -14400,
        currency: 'USD',
        google_mid: '/m/07zkz4n',
      },
    ],
    ETF: [],
    index: [],
    mutual_fund: [],
    currency: [],
    futures: [],
  },
};
export const fetchMarketTrendsApi = async () => {
  const options = {
    method: 'GET',
    url: 'https://real-time-finance-data.p.rapidapi.com/market-trends',
    params: {
      trend_type: 'GAINERS',
      country: 'us',
      language: 'en',
    },
    headers: {
      'X-RapidAPI-Key': API_KEY,
      'X-RapidAPI-Host': 'real-time-finance-data.p.rapidapi.com',
    },
  };

  try {
    // const response = await axios.request(options);
    // return response.data.data.trends;
    return DATA.data.trends;
  } catch (error: any) {
    throw error;
  }
};

export const fetchSearchResultsApi = async (searchQuery: string) => {
  const options = {
    method: 'GET',
    url: 'https://real-time-finance-data.p.rapidapi.com/search',
    params: {
      query: searchQuery,
      language: 'en',
    },
    headers: {
      'X-RapidAPI-Key': API_KEY,
      'X-RapidAPI-Host': 'real-time-finance-data.p.rapidapi.com',
    },
  };

  try {
    // const response = await axios.request(options);
    // return response.data.data.stock;
    return DATA_SEARCH.data.stock;
  } catch (error: any) {
    throw error;
  }
};
